const CONFLICTS = [
  {
    id: 'israel-iran-gaza',
    name: 'Israel — Iran & Gaza',
    region: 'Middle East',
    countries: ['Israel', 'Iran', 'Palestine'],
    intensity: 'critical',
    status: 'active',
    color: '#DC2626',
    started: '2023-10-07',
    summary: 'Ongoing conflict between Israel and Hamas in Gaza, with Iran-linked escalations.',
    telegramChannels: ['OSINTdefender', 'warmonitor3', 'israelradar', 'MiddleEastSpectator'],
    keywords: ['Israel', 'Gaza', 'Iran', 'Hamas', 'IDF', 'West Bank', 'Hezbollah'],
    rssKeywords: ['israel war', 'gaza conflict', 'iran israel', 'hamas attack'],
    lat: 31.5,
    lng: 34.8,
  },
  {
    id: 'russia-ukraine',
    name: 'Russia — Ukraine',
    region: 'Eastern Europe',
    countries: ['Russia', 'Ukraine'],
    intensity: 'critical',
    status: 'active',
    color: '#2563EB',
    started: '2022-02-24',
    summary: 'Full-scale Russian invasion of Ukraine, ongoing since February 2022.',
    telegramChannels: ['intel_slava', 'ukraine_now', 'rybar', 'UkraineWarPosts', 'militarylandnet'],
    keywords: ['Ukraine', 'Russia', 'Zelensky', 'Putin', 'Donbas', 'Kharkiv', 'Kyiv', 'NATO'],
    rssKeywords: ['ukraine war', 'russia ukraine', 'donbas', 'kherson'],
    lat: 49.0,
    lng: 32.0,
  },
  {
    id: 'sudan-civil-war',
    name: 'Sudan Civil War',
    region: 'Africa',
    countries: ['Sudan'],
    intensity: 'high',
    status: 'active',
    color: '#D97706',
    started: '2023-04-15',
    summary: 'Civil war between Sudanese Armed Forces and Rapid Support Forces.',
    telegramChannels: ['conflictupdates', 'OSINTdefender'],
    keywords: ['Sudan', 'SAF', 'RSF', 'Khartoum', 'Darfur', 'civil war'],
    rssKeywords: ['sudan war', 'sudan conflict', 'khartoum fighting'],
    lat: 15.5,
    lng: 32.5,
  },
  {
    id: 'myanmar-civil-war',
    name: 'Myanmar Civil War',
    region: 'Southeast Asia',
    countries: ['Myanmar'],
    intensity: 'high',
    status: 'active',
    color: '#7C3AED',
    started: '2021-02-01',
    summary: 'Armed conflict between military junta and resistance forces following 2021 coup.',
    telegramChannels: ['conflictupdates', 'OSINTdefender'],
    keywords: ['Myanmar', 'Burma', 'junta', 'PDF', 'Tatmadaw', 'resistance'],
    rssKeywords: ['myanmar war', 'myanmar military', 'burma conflict'],
    lat: 19.0,
    lng: 96.0,
  },
  {
    id: 'sahel-crisis',
    name: 'Sahel Region Crisis',
    region: 'West Africa',
    countries: ['Mali', 'Niger', 'Burkina Faso'],
    intensity: 'medium',
    status: 'active',
    color: '#059669',
    started: '2012-01-01',
    summary: 'Ongoing jihadist insurgency across the Sahel region of West Africa.',
    telegramChannels: ['conflictupdates'],
    keywords: ['Mali', 'Niger', 'Burkina Faso', 'Sahel', 'jihadist', 'JNIM', 'Wagner'],
    rssKeywords: ['sahel conflict', 'mali attack', 'burkina faso'],
    lat: 15.0,
    lng: -2.0,
  },
  {
    id: 'china-taiwan',
    name: 'China — Taiwan Tensions',
    region: 'East Asia',
    countries: ['China', 'Taiwan'],
    intensity: 'medium',
    status: 'monitoring',
    color: '#DB2777',
    started: '1949-01-01',
    summary: 'Ongoing cross-strait tensions with military exercises and diplomatic pressure.',
    telegramChannels: ['OSINTdefender'],
    keywords: ['Taiwan', 'China', 'PLA', 'strait', 'invasion', 'Xi Jinping'],
    rssKeywords: ['taiwan strait', 'china taiwan', 'pla military'],
    lat: 23.5,
    lng: 121.0,
  },
  {
    id: 'north-korea',
    name: 'North Korea Tensions',
    region: 'East Asia',
    countries: ['North Korea', 'South Korea'],
    intensity: 'medium',
    status: 'monitoring',
    color: '#6B7280',
    started: '1950-01-01',
    summary: 'Ongoing tensions with missile tests and military provocations.',
    telegramChannels: ['OSINTdefender'],
    keywords: ['North Korea', 'DPRK', 'Kim Jong Un', 'missile', 'nuclear', 'Seoul'],
    rssKeywords: ['north korea missile', 'dprk test', 'korean peninsula'],
    lat: 40.0,
    lng: 127.0,
  },
  {
  id: 'india-pakistan-2025',
  name: 'India — Pakistan Tensions',
  region: 'South Asia',
  countries: ['India', 'Pakistan'],
  intensity: 7,
  status: 'active',
  color: '#F97316',
  started: '2025-01-01',
  summary: 'Brief description yahan likho.',
  telegramChannels: ['OSINTdefender', 'conflictupdates'],
  keywords: ['India', 'Pakistan', 'LOC', 'Kashmir'],
  rssKeywords: ['india pakistan', 'kashmir conflict'],
  lat: 30.0,
  lng: 73.0,
},
  {
    id: 'haiti-crisis',
    name: 'Haiti Gang Crisis',
    region: 'Caribbean',
    countries: ['Haiti'],
    intensity: 'high',
    status: 'active',
    color: '#EA580C',
    started: '2021-07-07',
    summary: 'Severe gang violence following presidential assassination destabilizing the country.',
    telegramChannels: ['conflictupdates'],
    keywords: ['Haiti', 'gang', 'Port-au-Prince', 'G9', 'violence', 'humanitarian'],
    rssKeywords: ['haiti gang', 'haiti violence', 'haiti crisis'],
    lat: 18.9,
    lng: -72.3,
  },
];

module.exports = CONFLICTS;
