const CONFLICTS = [
  {
    id: 'israel-iran-gaza',
    name: 'Israel — Iran & Gaza',
    region: 'Middle East',
    countries: ['Israel', 'Iran', 'Palestine'],
    intensity: 'critical',
    status: 'active',
    color: '#DC2626',
    started: '2023-10-07',
    summary: 'Ongoing conflict between Israel and Hamas in Gaza, with Iran-linked escalations.',
    telegramChannels: ['OSINTdefender', 'warmonitor3', 'israelradar', 'MiddleEastSpectator'],
    keywords: ['Israel', 'Gaza', 'Iran', 'Hamas', 'IDF', 'West Bank', 'Hezbollah'],
    rssKeywords: ['israel war', 'gaza conflict', 'iran israel', 'hamas attack'],
    lat: 31.5,
    lng: 34.8,
  },
  {
    id: 'russia-ukraine',
    name: 'Russia — Ukraine',
    region: 'Eastern Europe',
    countries: ['Russia', 'Ukraine'],
    intensity: 'critical',
    status: 'active',
    color: '#2563EB',
    started: '2022-02-24',
    summary: 'Full-scale Russian invasion of Ukraine, ongoing since February 2022.',
    telegramChannels: ['intel_slava', 'ukraine_now', 'rybar', 'UkraineWarPosts', 'militarylandnet'],
    keywords: ['Ukraine', 'Russia', 'Zelensky', 'Putin', 'Donbas', 'Kharkiv', 'Kyiv', 'NATO'],
    rssKeywords: ['ukraine war', 'russia ukraine', 'donbas', 'kherson'],
    lat: 49.0,
    lng: 32.0,
  },
  {
    id: 'sudan-civil-war',
    name: 'Sudan Civil War',
    region: 'Africa',
    countries: ['Sudan'],
    intensity: 'high',
    status: 'active',
    color: '#D97706',
    started: '2023-04-15',
    summary: 'Civil war between Sudanese Armed Forces and Rapid Support Forces.',
    telegramChannels: ['conflictupdates', 'OSINTdefender'],
    keywords: ['Sudan', 'SAF', 'RSF', 'Khartoum', 'Darfur', 'civil war'],
    rssKeywords: ['sudan war', 'sudan conflict', 'khartoum fighting'],
    lat: 15.5,
    lng: 32.5,
  },
  {
    id: 'myanmar-civil-war',
    name: 'Myanmar Civil War',
    region: 'Southeast Asia',
    countries: ['Myanmar'],
    intensity: 'high',
    status: 'active',
    color: '#7C3AED',
    started: '2021-02-01',
    summary: 'Armed conflict between military junta and resistance forces following 2021 coup.',
    telegramChannels: ['conflictupdates', 'OSINTdefender'],
    keywords: ['Myanmar', 'Burma', 'junta', 'PDF', 'Tatmadaw', 'resistance'],
    rssKeywords: ['myanmar war', 'myanmar military', 'burma conflict'],
    lat: 19.0,
    lng: 96.0,
  },
  {
    id: 'sahel-crisis',
    name: 'Sahel Region Crisis',
    region: 'West Africa',
    countries: ['Mali', 'Niger', 'Burkina Faso'],
    intensity: 'medium',
    status: 'active',
    color: '#059669',
    started: '2012-01-01',
    summary: 'Ongoing jihadist insurgency across the Sahel region of West Africa.',
    telegramChannels: ['conflictupdates'],
    keywords: ['Mali', 'Niger', 'Burkina Faso', 'Sahel', 'jihadist', 'JNIM', 'Wagner'],
    rssKeywords: ['sahel conflict', 'mali attack', 'burkina faso'],
    lat: 15.0,
    lng: -2.0,
  },
  {
    id: 'china-taiwan',
    name: 'China — Taiwan Tensions',
    region: 'East Asia',
    countries: ['China', 'Taiwan'],
    intensity: 'medium',
    status: 'monitoring',
    color: '#DB2777',
    started: '1949-01-01',
    summary: 'Ongoing cross-strait tensions with military exercises and diplomatic pressure.',
    telegramChannels: ['OSINTdefender'],
    keywords: ['Taiwan', 'China', 'PLA', 'strait', 'invasion', 'Xi Jinping'],
    rssKeywords: ['taiwan strait', 'china taiwan', 'pla military'],
    lat: 23.5,
    lng: 121.0,
  },
  {
    id: 'north-korea',
    name: 'North Korea Tensions',
    region: 'East Asia',
    countries: ['North Korea', 'South Korea'],
    intensity: 'medium',
    status: 'monitoring',
    color: '#6B7280',
    started: '1950-01-01',
    summary: 'Ongoing tensions with missile tests and military provocations.',
    telegramChannels: ['OSINTdefender'],
    keywords: ['North Korea', 'DPRK', 'Kim Jong Un', 'missile', 'nuclear', 'Seoul'],
    rssKeywords: ['north korea missile', 'dprk test', 'korean peninsula'],
    lat: 40.0,
    lng: 127.0,
  },
  {
    id: 'india-pakistan-2025',
    name: 'India — Pakistan Tensions',
    region: 'South Asia',
    countries: ['India', 'Pakistan'],
    intensity: 7,
    status: 'active',
    color: '#F97316',
    started: '2025-01-01',
    summary: 'Escalating tensions between nuclear-armed neighbours over Kashmir and cross-border incidents.',
    telegramChannels: ['OSINTdefender', 'conflictupdates'],
    keywords: ['India', 'Pakistan', 'LOC', 'Kashmir', 'Modi', 'nuclear'],
    rssKeywords: ['india pakistan', 'kashmir conflict', 'loc ceasefire'],
    lat: 30.0,
    lng: 73.0,
  },
  {
    id: 'haiti-crisis',
    name: 'Haiti Gang Crisis',
    region: 'Caribbean',
    countries: ['Haiti'],
    intensity: 'high',
    status: 'active',
    color: '#EA580C',
    started: '2021-07-07',
    summary: 'Severe gang violence following presidential assassination destabilizing the country.',
    telegramChannels: ['conflictupdates'],
    keywords: ['Haiti', 'gang', 'Port-au-Prince', 'G9', 'violence', 'humanitarian'],
    rssKeywords: ['haiti gang', 'haiti violence', 'haiti crisis'],
    lat: 18.9,
    lng: -72.3,
  },

  // ── NEW: USA — IRAN ──────────────────────────────────────────────

  {
    id: 'usa-iran-tensions',
    name: 'USA — Iran Tensions',
    region: 'Middle East',
    countries: ['USA', 'Iran', 'Israel'],
    intensity: 9,
    status: 'active',
    color: '#B91C1C',
    started: '1979-11-04',
    summary: 'Decades-long hostility between Washington and Tehran escalating sharply in 2025. US sanctions, nuclear standoff, Iranian proxy attacks on US forces across Middle East, and direct military exchanges. Iran nuclear program approaching weapons-grade enrichment threshold while US and Israel weigh military options.',
    telegramChannels: ['OSINTdefender', 'MiddleEastSpectator', 'warmonitor3', 'israelradar'],
    keywords: ['USA', 'Iran', 'sanctions', 'nuclear', 'IRGC', 'proxy war', 'Trump', 'Khamenei', 'enrichment', 'strikes', 'Pentagon'],
    rssKeywords: ['us iran tensions', 'iran nuclear', 'iran sanctions', 'irgc attack', 'iran us military', 'iran nuclear deal', 'iran enrichment', 'iran proxy'],
    lat: 32.0,
    lng: 53.0,
  },

  // ── NEW: ENERGY & TRADE MONITORING ──────────────────────────────

  {
    id: 'strait-of-hormuz',
    name: 'Strait of Hormuz — Maritime Security',
    region: 'Middle East',
    countries: ['Iran', 'UAE', 'Oman', 'USA'],
    intensity: 'high',
    status: 'active',
    color: '#0EA5E9',
    started: '2019-05-01',
    summary: 'Strategic chokepoint through which ~20% of global oil supply passes. Iran regularly threatens closure amid regional tensions. US Navy 5th Fleet maintains presence. Houthi attacks and Iranian seizures of tankers create ongoing maritime security crisis.',
    telegramChannels: ['OSINTdefender', 'MiddleEastSpectator', 'warmonitor3'],
    keywords: ['Strait of Hormuz', 'Iran', 'tanker', 'oil shipment', 'US Navy', 'IRGC', 'maritime security', 'Houthi', 'Red Sea', 'chokepoint'],
    rssKeywords: ['strait of hormuz', 'iran tanker', 'hormuz closure', 'red sea attack', 'houthi ship', 'naval blockade', 'oil shipment'],
    lat: 26.5,
    lng: 56.5,
  },

  {
    id: 'usa-global-standing',
    name: 'USA — Global Order in Crisis',
    region: 'Global',
    countries: ['USA', 'Canada', 'EU', 'China', 'NATO'],
    intensity: 8,
    status: 'active',
    color: '#6366F1',
    started: '2025-01-20',
    summary: 'The United States under Trump 2.0 is simultaneously alienating allies, launching trade wars, threatening to annex Canada and Greenland, gutting foreign aid, and withdrawing from international institutions — while calling it "winning". NATO allies are quietly updating their threat assessments to include Washington. The rest of the world watches, equal parts horrified and entertained.',
    telegramChannels: ['OSINTdefender', 'conflictupdates'],
    keywords: ['Trump', 'tariffs', 'trade war', 'NATO', 'Greenland', 'Canada', 'DOGE', 'US allies', 'isolationism', 'America First', 'EU', 'China tariffs'],
    rssKeywords: ['trump tariffs', 'us trade war', 'nato trump', 'trump canada', 'trump greenland', 'us allies', 'trump eu', 'america first policy', 'us china trade', 'trump foreign policy'],
    lat: 38.9,
    lng: -77.0,
  },

  {
    id: 'global-energy-crisis',
    name: 'Global Oil & Gas Market Crisis',
    region: 'Global',
    countries: ['USA', 'Russia', 'Saudi Arabia', 'Iran', 'Iraq', 'Venezuela'],
    intensity: 'medium',
    status: 'monitoring',
    color: '#F59E0B',
    started: '2021-01-01',
    summary: 'Global crude oil and natural gas markets under pressure from geopolitical conflicts, OPEC+ production decisions, sanctions on Russia, and energy transition policies. War in Ukraine, Middle East instability, and US-China tensions directly impact energy prices and supply chains worldwide.',
    telegramChannels: ['OSINTdefender', 'conflictupdates'],
    keywords: ['crude oil', 'natural gas', 'OPEC', 'energy crisis', 'oil price', 'LNG', 'pipeline', 'sanctions', 'Brent crude', 'WTI', 'energy supply'],
    rssKeywords: ['crude oil price', 'opec production', 'natural gas supply', 'energy crisis', 'oil sanctions', 'lng export', 'oil market', 'brent crude', 'wti oil'],
    lat: 25.0,
    lng: 50.0,
  },
];

module.exports = CONFLICTS;